// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System.Collections.Generic;
    using Coherence.ProtocolDef;
    
    public static class Archetypes
    {
        public const int _f56c32abdf848d041964eb9b807eddfeIndex = 0;

        public static readonly EntityArchetype[] Definitions =
		{
            new EntityArchetype() // _f56c32abdf848d041964eb9b807eddfe
            {
                LODs = new EntityArchetypeLOD[]
                {
                    new EntityArchetypeLOD
                    {
                        Level = 0,
                        Distance = 0,
                        ComponentReplacement = new Dictionary<uint, uint>
                        {
                            { 0, Definition.InternalArchetype_f56c32abdf848d041964eb9b807eddfe_WorldPosition_LOD0 },
                            { 1, Definition.InternalArchetype_f56c32abdf848d041964eb9b807eddfe_WorldOrientation_LOD0 },
                            { 17, Definition.InternalArchetype_f56c32abdf848d041964eb9b807eddfe_GenericScale_LOD0 },
                            { 166, Definition.InternalArchetype_f56c32abdf848d041964eb9b807eddfe__f56c32abdf848d041964eb9b807eddfe_5150605711725245781_LOD0 },
                        },
                        ComponentsExcluded = new uint[] 
                        {
                        },
                    },
                },
            },
		};
    
        public static Dictionary<string, int> IndexForName = new Dictionary<string, int>() 
        {
            { "_f56c32abdf848d041964eb9b807eddfe", 0 },
        };
    }     
    

}